--------------------------------------------------------
--  DDL for Table MA_BEOBACHTUNGEN
--------------------------------------------------------

  CREATE TABLE "MA_BEOBACHTUNGEN" 
   (	"ID_B" NUMBER(38,0), 
	"UZ_VON" TIMESTAMP (6), 
	"VERIFIZIERT" NUMBER(38,0), 
	"ID_V" NUMBER(38,0), 
	"ID_P" NUMBER(38,0), 
	"ID_O" NUMBER(38,0), 
	"UZ_BIS" TIMESTAMP (6), 
	"BEMERKUNG" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C001932914
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001932914" ON "MA_BEOBACHTUNGEN" ("ID_B") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MA_BEOBACHTUNGEN
--------------------------------------------------------

  ALTER TABLE "MA_BEOBACHTUNGEN" MODIFY ("VERIFIZIERT" NOT NULL ENABLE);
 
  ALTER TABLE "MA_BEOBACHTUNGEN" MODIFY ("ID_V" NOT NULL ENABLE);
 
  ALTER TABLE "MA_BEOBACHTUNGEN" MODIFY ("ID_P" NOT NULL ENABLE);
 
  ALTER TABLE "MA_BEOBACHTUNGEN" MODIFY ("ID_O" NOT NULL ENABLE);
 
  ALTER TABLE "MA_BEOBACHTUNGEN" ADD CHECK (Verifiziert in (0, 1)) ENABLE;
 
  ALTER TABLE "MA_BEOBACHTUNGEN" ADD PRIMARY KEY ("ID_B")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MA_BEOBACHTUNGEN
--------------------------------------------------------

  ALTER TABLE "MA_BEOBACHTUNGEN" ADD FOREIGN KEY ("ID_V")
	  REFERENCES "MA_VOGEL" ("ID_V") ENABLE;
 
  ALTER TABLE "MA_BEOBACHTUNGEN" ADD FOREIGN KEY ("ID_P")
	  REFERENCES "MA_PERSONEN" ("ID_P") ENABLE;
 
  ALTER TABLE "MA_BEOBACHTUNGEN" ADD FOREIGN KEY ("ID_O")
	  REFERENCES "MA_ORT" ("ID_O") ENABLE;
