--------------------------------------------------------
--  DDL for Table MA_ORT
--------------------------------------------------------

  CREATE TABLE "MA_ORT" 
   (	"ID_O" NUMBER(38,0), 
	"AREA" VARCHAR2(255 BYTE), 
	"LAND" VARCHAR2(255 BYTE), 
	"REGION" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C001932907
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001932907" ON "MA_ORT" ("ID_O") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MA_ORT
--------------------------------------------------------

  ALTER TABLE "MA_ORT" MODIFY ("AREA" NOT NULL ENABLE);
 
  ALTER TABLE "MA_ORT" MODIFY ("LAND" NOT NULL ENABLE);
 
  ALTER TABLE "MA_ORT" ADD PRIMARY KEY ("ID_O")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
