--------------------------------------------------------
--  DDL for Table MA_VOGEL
--------------------------------------------------------

  CREATE TABLE "MA_VOGEL" 
   (	"ID_V" NUMBER(38,0), 
	"NAME_ENG" VARCHAR2(255 BYTE), 
	"NAME_DEU" VARCHAR2(255 BYTE), 
	"NAME_LAT" VARCHAR2(255 BYTE), 
	"CATEGORY" VARCHAR2(255 BYTE), 
	"FAMILY" VARCHAR2(255 BYTE), 
	"SORTORDER" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C001932890
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001932890" ON "MA_VOGEL" ("ID_V") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MA_VOGEL
--------------------------------------------------------

  ALTER TABLE "MA_VOGEL" ADD PRIMARY KEY ("ID_V")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
